# PteroStats config
# If you need help, join our discord server here: https://discord.gg/zv6maQRah3

# Bot Info's
token: 'OTY4NzkyMDk3MzYyNjk4MjUw.Ymj_8w.XzvtHh9Zf7AwwtbKsgvnMda_DVA' # Put bot token here, check https://discord.dev to create and get bot token
botstatus:
  enable: false # Enable Custom Status (MUST BE "true" OR "false")
  text: 'Hosting Panel' # Bot Status Message
  type: 'WATCHING' # Bot Status Type. Ex: PLAYING, WATCHING, LISTENING, STREAMING

# Channel and RefreshTime Configuration
channel: '960536798499590155' # Put channel id here where the embed will be sended
refreshtime: 60 # Time when the embed edited/refreshed (MUST BE A SECONDS) (RECOMMENDED MORE THAN 20 SECONDS)

# Panel Info's
panel:
  url: 'https://panel.wildreftmc.my.id' # Put panel url here. Example: https://panel.purenodes.net
  adminkey: 'R64o3jAq0NmVwTZoyKnsdG6CYxcUyfPTKs39t2n2GS2MP3CT' # Put Admin Apikey here. check https://your.host.url/admin/api (your.host.url is an example link) to get the Admin ApiKey

# Embed Configuration
embed: 
  title: 'EMBED TITLE' # Embed Title here. Ex: PureNodes Stats
  color: 'E5BE11' # Embed Hex color here.
  description: 
    enable: false # Enable Embed Description (MUST BE "true" OR "false")
    text: 'EMBED DESCRIPTION' # Embed Description
  footer: 
    enable: true # Enable Embed Footer (MUST BE "true" OR "false")
    text: 'By Hirzi#8701' # Embed Footer
  timestamp: true # Enable Embed TimeStamp (MUST BE "true" OR "false")

# Status Message Configuration
status:
  online: ':green_circle: Online' # Message if the status is Online
  offline: ':red_circle: Offline' # Message if the status is Offline
  check: ':orange_circle: Checking' # Message if the status is Checking

# Node Resource
resource:
  enable: true # Enable resource option ex [Ram: 2gb/5gb] bellow node name (MUST BE "true" OR "false")
  servers: true # Enable Total server on the node to resource text (MUST BE "true" OR "false")
  allocations: true # Enable Total Allocation on the node to resource text (MUST BE "true" OR "false")
  location: true # Enable location short name on the node to resource text (MUST BE "true" OR "false")
  unit: 'gb' # Must be 'mb', 'gb', or 'percent'

# Developers feature
debug: false # Enable and Disable debug log to console
debugaxios: false #Enable and Disable axios error logs
